apiVersion: custompodautoscaler.com/v1alpha1
kind: CustomPodAutoscaler
metadata:
  name: locust-autoscaler-example
spec:
  template:
    spec:
      containers:
      - name: locust-autoscaler-example
        image: locust-pod-autoscaler-example:latest
        imagePullPolicy: Always
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fibonacci
  config: 
    - name: interval
      value: "10000"
    - name: locustHost
      value: "http://fibonacci:5000"